#Adempiere
#Fri Feb 09 17:10:53 VET 2024
DB|CONFIG_DB_CONNECTION_TEST_QUERY=xyz@CONFIG_DB_CONNECTION_TEST_QUERY@
DB|CONFIG_DB_IDLE_TIMEOUT=xyz@CONFIG_DB_IDLE_TIMEOUT@
DB|CONFIG_DB_CONNECTION_TIMEOUT=xyz@CONFIG_DB_CONNECTION_TIMEOUT@
DB|CONFIG_DB_MINIMUM_IDLE=xyz@CONFIG_DB_MINIMUM_IDLE@
DB|CONFIG_DB_MAXIMUM_POOL_SIZE=xyz@CONFIG_DB_MAXIMUM_POOL_SIZE@
DB|CONFIG_DB_MAX_LIFETIME=xyz@CONFIG_DB_MAX_LIFETIME@
DB|CONFIG_DB_KEEPALIVE_TIME=xyz@CONFIG_DB_KEEPALIVE_TIME@
CDate=a459088bb7ab09e324d9596c5a2f49f55a323bd46b91d9b0
